image: maven:3.6.3-jdk-11

stages:
  - test-antlr
  - test-frontend
  - test-backend
  - test-extension

test-antlr:
  stage: test-antlr
  script:
    - echo "Building"
    - make clean all
    - ./testgrun

test-frontend:
  stage: test-frontend
  script:
    - echo "Testing the front end"
    - make clean all
    - ./gradlew test
    # test lexing
    # test parsing
    # test semantics

test-backend:
  stage: test-backend
  script:
    - echo "Testing the back end"
    # test code generation

test-extension:
  stage: test-extension
  script:
    - echo "Testing the extension"
