#!/bin/bash

#make

./compile $1
filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"

echo "name": $filename
arm-linux-gnueabi-gcc -o FILENAME1 -mcpu=arm1176jzf-s -mtune=arm1176jzf-s $filename.s
qemu-arm -L /usr/arm-linux-gnueabi/ FILENAME1
echo "Exit Code: " $?
