#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

java -jar wacc_23-all-1.0-SNAPSHOT.jar $1 > /dev/null 2>&1

exit $?